### ISSUE TITLE
Add `HedTag.validate` to  `HedTag.__init__` and `HedTag.add_row` 

### ISSUE THREAD

**Issue by oruebel** [hed-standard/ndx-hed#10]
Add `HedTag.validate` to  `HedTag.__init__` and `HedTag.add_row` methods to raise `ValueErrors` for invalid hedtag string values during creation and addition. This is to enforce that `HedTag` always contains only valid hed strings.

**Comment by VisLab** [comment]
In latest version hed_version is required and validation is done both in constructor and in add_row.  The validation now throws ValueError (PR #14)
