### ISSUE TITLE
Remove configuration from `setup.py` and `setup.cfg` in favor of  `pyproject.toml` . 

### ISSUE THREAD

**Issue by oruebel** [hed-standard/ndx-hed#11]
Remove configuration from `setup.py` and `setup.cfg` in favor of  `pyproject.toml` . 

Check that tests are working correctly when configured with `pyproject.toml`

**Comment by VisLab** [comment]
PR #12 addresses this to some extent.

**Comment by VisLab** [comment]
Project now uses .toml   (PR # 13).
